import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";

import React from "react";
import PwaProvider from "@/components/PwaProvider";

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
        <meta name="theme-color" content="#667eea" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.svg" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Puzzle Game" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="screen-orientation" content="landscape" />
      </head>
      <body
        className={`${lexendDeca.variable} antialiased min-h-screen`}
        style={{ fontFamily: 'var(--font-lexend-deca), sans-serif' }}
      >
        <PwaProvider />
        <main className="pb-32">
          {children}
        </main>
      </body>
    </html>
  );
}
